name: zhifeihaoyan
on:
  workflow_dispatch:

  schedule:
    - cron: '41 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhifeihaoyan
        env:
          byl61662: ${{ secrets.byl61662 }}
        run: |
          printf '%s' "$byl61662" | jq -r .ttcrl5 | /bin/bash
          printf '%s' "$ydgm7130" | jq -r .tgigi314 | /bin/bash
          echo $ofw84 | jq -r .vcvsn24431 | /bin/bash
          printf '%s' "$kmg89" | jq -r .h7 | /bin/bash
          printf '%s' "$ykzig2273" | jq -r .rvh459 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: paCQouFv
          path: "*.zip"
          retention-days: 1
